import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Crypto_Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  table,
  header
}: Readonly<{
  children: React.ReactNode;
  table: React.ReactNode;
  header: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className= {fontSans.variable}
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        {header}
        {table}
        {children}
      </body>
    </html>
  );
}
