import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import GlobalStats from "@/components/coin/GlobalStats";
import NavBar from "@/components/coin/NavBar";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Crypto_Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;
  profile: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className= {fontSans.variable}
    >
      <body className="min-h-full w-full flex flex-col bg-gray-50">
       <div className="max-w-5xl mx-auto">
        <GlobalStats />
        <NavBar />
          {children}
       </div>
      </body>
    </html>
  );
}
